[package]
name        = "evento"
version     = "0.0.1"
description = "programming language prototype"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>","DeepSeek"]
license     = "MIT"
edition     = "2024"

[dependencies]

[[bin]]
name  = "evento"
path  = "src/rs.rs"
test  = false
debug = true

[features]
# hw
pc       = ["i5"]
pillF103 = ["stm32f103"]
# cpu
i5        = ["x86_64"]
stm32f103 = ["cortexM4"]
# arch
x86_64   = ["linux"]
cortexM  = ["bare"]
cortexM4 = ["cortexM"]
# os
linux = []
bare  = []
